(library
 (name static_r_tree)
 (modules static_r_tree hilbert)
 (preprocess
  (pps ppx_inline_test))
 (inline_tests))

(executables
 (names
  corine
  draw_clc
  render_clc
  check_overlaps
  extract_tiles
  compress_dem
  render_dem
  triangulate_test
  polygon_to_svg
  analyze_polygon
  triangulation_tests)
 (modules
  (:standard \ static_r_tree hilbert))
 (libraries static_r_tree sqlite3 str tsdl tgls.tgles3 zip yojson unix)
 (ocamlopt_flags
  (-cclib -lGLESv2)))

(rule
 (alias runtest)
 (deps
  (glob_files test_polygons/*))
 (action
  (with-stdout-to
   triangulation_tests.output
   (with-accepted-exit-codes
    (or 0 1)
    (run ./triangulation_tests.exe)))))

(rule
 (alias runtest)
 (action
  (diff triangulation_tests.expected triangulation_tests.output)))
