(env
 (_
  (js_of_ocaml
   (compilation_mode whole_program))
  (wasm_of_ocaml
   (compilation_mode whole_program))))

(executables
 (names viewer)
 (libraries mountains yojson brr lwt)
 (modes js wasm)
 (js_of_ocaml
  (javascript_files inflate.js))
 (wasm_of_ocaml
  (javascript_files inflate.js)
  (wasm_files inflate.wat)))

(executables
 (names worker)
 (libraries mountains yojson brr lwt)
 (modes js)
 (js_of_ocaml
  (javascript_files inflate.js)))

(rule
 (target
  (dir data))
 (alias all)
 (deps
  (glob_files_rec ../../data/**))
 (action
  (progn
   (run cp -r ../../data %{target}))))

(rule
 (target
  (dir assets))
 (alias all)
 (deps
  (glob_files_rec ../../assets/**))
 (action
  (progn
   (run mkdir %{target})
   (run cp %{deps} %{target}))))

(rule
 (target service_worker.bc.js)
 (alias all)
 (deps service_worker/service_worker.bc.js)
 (action
  (copy %{deps} %{target})))

(alias
 (name all)
 (deps index.html manifest.json icon192.png icon512.png))

(rule
 (alias web)
 (action
  (run python3 -m http.server -d .))
 (deps
  index.html
  data
  viewer.bc.js
  viewer.bc.wasm.js
  service_worker.bc.js
  manifest.json
  icon192.png
  icon512.png
  compute.wasm
  decompress_tile.wasm
  worker.bc.js))

(rule
 (target compute.wasm)
 (deps compute.c)
 (mode promote)
 (action
  (run
   clang
   -Ofast
   -msimd128
   --no-standard-libraries
   --target=wasm32
   -Wl,--no-entry
   -Wl,--import-memory
   -Wa,--no-type-check
   -o
   %{target}
   %{deps})))

(rule
 (target decompress_tile.wasm)
 (deps decompress_tile.wat)
 (action
  (run
   wasm-opt
   -O4
   --enable-simd
   --enable-bulk-memory
   --enable-multimemory
   %{deps}
   -o
   %{target})))

(rule
 (target decode_clc.wasm)
 (deps decode_clc.wat)
 (action
  (run
   wasm-opt
   -O4
   --enable-simd
   --enable-bulk-memory
   --enable-multimemory
   %{deps}
   -o
   %{target})))
